baseURL = 'https://y30n9ju1v.github.io/develop/'
locale = 'en-us'
title = "y30n9ju1v's Develops"
theme = "hextra"

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[params.math]
  enable = true
  engine = "katex"

[markup.goldmark.extensions.passthrough]
  enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  block = [["$$", "$$"]]
  inline = [["$", "$"]]

[markup.asciidocExt]
  extensions = []
  workingFolderCurrent = true
  trace = false
  failureLevel = "fatal"
  noHeaderOrFooter = true
  safeMode = "unsafe"
  sectionNumbers = false
  verbose = false

[markup.asciidocExt.attributes]
  source-highlighter = "rouge"
  rouge-style = "github"
  stem = "latexmath"
  pp = "++"
  us = "_"

[security.exec]
  allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^tailwindcss$', '^asciidoctor$']
